### PR TITLE
feat(charts): add default policy and storageclass

### PR DESCRIPTION
**Pull request by shubham14bajpai**
Signed-off-by: shubham <shubham.bajpai@mayadata.io>

This PR adds a default jiva volume policy and a default storageclass while deploying using helm charts

### CODE REVIEW

**Review by niladrih — APPROVED** [review]
Could you move the `localpv-provisioner` block from line 186 of values.yaml to the end (i.e. after `replicas: 3` line)?
I think it looks better it the main chart and sub chart sections are separate.

LGTM otherwise

**Review by niladrih — CHANGES_REQUESTED** [review]
Please add the README configuration table entries for these values.yaml parameters.

**Review by prateekpandey14 — APPROVED** [review]
lgtm

**Review by niladrih — APPROVED** [review]
LGTM

**Pull request merged**
