### PR TITLE
fix(provisioning): corrected the prometheus scrape annotation syntax. 

### LINKED ISSUE #173: Prometheus metrics are not exported for Jiva Volumes
Through deployment of Jiva Operator (v3.0.5), I found that Prometheus (v.2.26) is not able to scrape metrics for the Jiva volumes that are provisioned in my Kubernetes cluster. Upon closer diagnosis, I found that each Jiva controller deployment (`pvc-<uuid>-jiva-ctrl`) created in response to requesting a PVC, uses an invalid Prometheus scrape annotation below: 

`prometheus.io/scrap: "true"`

The correct annotation should be: 

prometheus.io/scrap**e**: "true"

After manually updating my Jiva volume deployment, I was able to Validate Prometheus could now scape my Jiva volumes.

### PR DESCRIPTION
**Pull request by shazadbrohi**
Signed-off-by: Shazad Brohi <brohishazad@gmail.com>

**Why is this PR required? What issue does it fix?**:
_Fixes #173 

**What this PR does?**:
Corrects the Prometheus scrape annotation for provisioned Jiva controller deployments from `prometheus.io/scrap: "true"` to `prometheus.io/scrape: "true"`

**Does this PR require any upgrade changes?**:
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
Updated the annotation to match the correct one here and was validated Prometheus was able to scrape the Jiva Volume metrics from my provisioned Jiva volume. 

**Any additional information for your reviewer?** : 
N/A

**Checklist:**
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`. 
- [x] Has the change log section been updated? 
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Does this PR change require updating Helm Chart? If yes, mention the Helm Chart PR #<PR number>
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track: 
- [ ] (Optional) If documentation changes are required, which issue  https://github.com/openebs/website is used to track them:

### CODE REVIEW

**Review by shubham14bajpai — APPROVED** [review]
LGTM. Thank you for the PR.

**Comment by shazadbrohi** [comment]
Thanks @shubham14bajpai! In which release version will this change be incorporated?

**Comment by shubham14bajpai** [comment]
I have [cherry-picked](https://github.com/openebs/jiva-operator/pull/175) the changes for the upcoming 3.1.0 release and it will be available by next month.

**Comment by shazadbrohi** [comment]
Thank you for the update. We need these changes by Jan 7th if possible.

**Pull request merged**
